= Routine Implementation

== Overview

BMM provides a hook for defining routine implementations, i.e. adding a routine _body_ consisting of _statements_. This is formalised using the classes `BMM_STATEMENT_ITEM`, `BMM_STATEMENT_BLOCK` and `BMM_STATEMENT`, as shown in the UML view below.

[.text-center]
.Features for routine definition
image::{uml_diagrams_uri}/LANG-bmm.statement.svg[id=LANG-statement, align="center"]

The use of the three-class hierarchy pattern allows a Routine `_body_` to just be a simple statement, with no block structure. The class `BMM_STATEMENT` is abstract, allowing specific statement meta-models to be developed in which the 'statement' meta-types inherit from this class.

This facility is primarily provided to support the definition of higher-level languages by embedding them in the outer BMM meta-model.

== Assignment

xxx

== Procedure Call

xxxx

== Assertions

xxx

== Decision Structures

xxx

== Class Definitions

include::{uml_export_dir}/classes/bmm_statement_item.adoc[]
include::{uml_export_dir}/classes/bmm_statement_block.adoc[]
include::{uml_export_dir}/classes/bmm_statement.adoc[]

include::{uml_export_dir}/classes/bmm_procedure_call.adoc[]
include::{uml_export_dir}/classes/bmm_assignment.adoc[]
include::{uml_export_dir}/classes/bmm_assertion.adoc[]

include::{uml_export_dir}/classes/bmm_decision_group.adoc[]
include::{uml_export_dir}/classes/bmm_decision_branch.adoc[]
include::{uml_export_dir}/classes/bmm_condition_chain.adoc[]
include::{uml_export_dir}/classes/bmm_condition_branch.adoc[]
include::{uml_export_dir}/classes/bmm_case_group.adoc[]
include::{uml_export_dir}/classes/bmm_case_branch.adoc[]

