= Entities

== Overview

The key elements of the BMM model are meta-classes representing _classes_ and _types_, respectively definers and instance templates for run-time objects, known in BMM as _entities_. BMM accordingly defines meta-types for entity, class, and various flavours of type, as shown in the following UML diagram.

[.text-center]
.`base.bmm.core.entity` Package - Entities
image::{uml_diagrams_uri}/LANG-bmm.core.entity.svg[id=core_entity, align="center"]

The general structure of a concrete model expressed in BMM consists of a set of classes, whose features (properties, routines) are each typed by an instance of of a descendant of the meta-class `BMM_TYPE`.

The top meta-class `BMM_ENTITY` defines two properties inherent in classes defined in a model, and derived in resulting types: `_is_abstract_` and `_is_primitive_`. The Boolean attribute `_is_abstract_` indicates an abstract class in a BMM model, or a type based on an abstract class - i.e. one that cannot be directly instantiated.

The attribute `_is_primitive_` indicates that a class in a BMM model is considered to be part of a primitive type set (typically corresponding to primitive types in another type system); for types, it is simply a feature derived from the `_defining_class_`. Primitive status has no effect on BMM model semantics, and is provided as a convenience for visualisation and type-system mapping.

== The Class / Type Distinction

One of the foundational distinctions in the BMM is between _class_ and _type_, in common with the type systems of the modern forms of most object-oriented languages, but in contrast to the UML meta-model. Classes are _definitional_ entities, while 'type' has two meanings: 

* as the static (design time) type of a class feature (property or function result), and 
* as the dynamic (run-time) type of the object referred to by or computed by that feature. 

The simplest example of the former case is the typing of properties, as shown below.

[.text-center]
.BMM entities
image::{diagrams_uri}/bmm_entities.svg[id=bmm_entities, align="center"]

In the latter case, a type is understood as the _generator_ of instances. In a static model, types are references. For simple types, they refer to the corresponding simple class definition, but for generic types, they refer to a particular usage of a generic class definition. A generic class may generate numerous generic types.

This central division is reflected in the two classes `BMM_CLASS` and `BMM_TYPE`, and their respective descendants, which are described in the following sections.

== Class Definitions

include::{uml_export_dir}/classes/bmm_entity.adoc[]
