= Literal Values

== Overview

With a typical formal model, there is a need for formal representation of literal values. This is needed to support constant declarations, 'default values' (a UML concept), enumeration literals and literal routine calls (see next section). In BMM, all such values have as their meta-type the type `BMM_LITERAL_VALUE` or a descendant. The UML model of these types is shown below.

[.text-center]
.`base.bmm.core.literal_value` package - Literal Values
image::{uml_diagrams_uri}/LANG-bmm.core.literal_value.svg[id=core_literal_value, align="center"]

In the above model, the sub-types of `BMM_LITERAL_VALUE` are limited to those that are generically applicable in any other part of the model.

When a BMM model is instantiated in its in-memory form, e.g. in a BMM modelling tool, any literal values in the model such as constant values (e.g. `Real pi = 3.1415926`), default values (e.g. `Person.name: String = "(unknown)"`) etc are instances of two 'types':

* their declared types withing the model, e.g. `Real`, `String`;
* the meta-type `BMM_LITERAL_VALUE`, which is instantiated to represent the value object within the model.

The literal value of any such object is represented by the `_value_literal_` field within its `BMM_LITERAL_VALUE`. This is assumed to carry a value expressed in a syntax known to the model processing environment within which the BMM model is being used. This may be a programming language syntax, JSON, or any other serialisable format.

In principle, a `BMM_LITERAL_VALUE` descendant can be created to directly match the concrete type of any value in a model, including any primitive type, and also structured values. The BMM model described here currently includes only descendants corresponding to types directly needed in the BMM, which includes two primitive types (`String` and `Integer`) needed for constrained types (aka enumerations), tuples, which are described below, and routine calls, described in <<Functional Elements>>.

In practice many literal values appearing in a BMM model may be instantiated simply as instances of `BMM_LITERAL_VALUE`, with their value stored in the `_value_literal_` field.

If it was desired to create a full set of 'native' types for BMM, in the way supplied for UML in the UML Standard Profile, specific descendants would be added to the meta-type classes `BMM_SIMPLE_TYPE` and `BMM_GENERIC_TYPE`, as well as `BMM_LITERAL_VALUE`, which would allow such instances to be directly representable in the internal BMM type system. This would still need to be ultimately mapped to the types actually available in any language in which BMM is implemented.

== Class Definitions

include::{uml_export_dir}/classes/bmm_literal_value.adoc[]
include::{uml_export_dir}/classes/bmm_string_value.adoc[]
include::{uml_export_dir}/classes/bmm_integer_value.adoc[]
include::{uml_export_dir}/classes/bmm_boolean_value.adoc[]
