= Routine Implementation

== Overview

BMM provides a hook for defining routine implementations, i.e. adding a routine _body_ consisting of _statements_. This is formalised using the classes `BMM_STATEMENT_ITEM`, `BMM_STATEMENT_BLOCK` and `BMM_STATEMENT`, as shown in the UML view below.

[.text-center]
.Features for routine definition
image::{uml_diagrams_uri}/LANG-bmm.core.feature-routine.svg[id=LANG-routine_definition, align="center"]

The use of the three-class hierarchy pattern allows a Routine `_body_` to just be a simple statement, with no block structure. The class `BMM_STATEMENT` is abstract, allowing specific statement meta-models to be developed in which the 'statement' meta-types inherit from this class.

This facility is primarily provided to support the definition of higher-level languages by embedding them in the outer BMM meta-model.

== Class Definitions

include::{uml_export_dir}/classes/bmm_statement_item.adoc[]
include::{uml_export_dir}/classes/bmm_statement_block.adoc[]
include::{uml_export_dir}/classes/bmm_statement.adoc[]
