=== BMM_ROUTINE_CALL Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_ROUTINE_CALL (abstract)_*

h|*Description*
2+a|A literal routine call, including closed arguments (if any) and potentially including open arguments. This allows a simple call like `calculate_age (dob="1987-09-13", today="2019-06-03")` but also curried function calls such as `format_structure (struct=?, style=3)`, where `struct` is an open argument.

h|*Inherit*
2+|`BMM_VALUE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `String`
a|Name of the routine being called.

h|*0..1*
|*closed_args*: `BMM_TUPLE`
a|Closed arguments of a routine call as a tuple of objects.

h|*0..1*
|*open_args*: `List<String>`
a|Optional list of names of open arguments of the call. If not provided, and the `_name_` refers to a routine with more arguments than supplied in `_closed_args_`, the missing arguments are inferred from the definition.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*type* (): `BMM_ROUTINE_SIGNATURE`
a|Static type inferred from literal value.
|===
