=== BMM_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_TYPE (abstract)_*

h|*Description*
2+a|Abstract idea of specifying a type in some context. This is not the same as 'defining' a class. A type specification is essentially a reference of some kind, that defines the type of an attribute, or function result or argument. It may include generic parameters that might or might not be bound. See subtypes.

h|*Inherit*
2+|`BMM_ENTITY`

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*is_primitive* (): `Boolean`
a|True if type is based only on a primitive class, or a collection thereof. Effected in descendants.

h|*1..1 +
(abstract)*
|*type_name* (): `String`
a|Formal string form of the type as per UML.

h|*1..1 +
(abstract)*
|*flattened_type_list* (): `List<String>`
a|Completely flattened list of type names, flattening out all generic parameters.

h|*1..1*
|*type_signature* (): `String`
a|Signature form of the type name, which for generics includes generic parameter constrainer types E.g. `Interval<T:Ordered>`.

Defaults to the value of `_type_name()_`.

h|*1..1 +
(abstract)*
|*unitary_type* (): `BMM_UNITARY_TYPE`
a|Type with any container abstracted away.

h|*1..1 +
(abstract)*
|*effective_type* (): `BMM_EFFECTIVE_TYPE`
a|Type with any container abstracted away, and any formal parameter replaced by its effective constraint type.
|===
