=== BMM_TUPLE_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_TUPLE_TYPE*

h|*Description*
2+a|Special type representing the type of a tuple, i.e. an array of any number of other types. This includes both container and unitary types, since tuple instances represent concrete objects.

Note that both open and closed generic parameters are allowed, as with any generic type, but open generic parameters are only valid within the scope of a generic class.

h|*Inherit*
2+|`BMM_EFFECTIVE_TYPE`

h|*Constants*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*base_name*: `String{nbsp}={nbsp}"Tuple"`
a|
h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*item_types*: `Hash<String,BMM_TYPE>`
a|List of types of the items of the tuple, keyed by purpose in the tuple.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*type_base_name* (): `String`
a|Result = `_base_name_`.

h|(effected)
|*is_primitive* (): `Boolean`
a|Result = `True`.

h|(effected)
|*is_abstract* (): `Boolean`
a|Result = `False`.
|===
