=== BMM_DEFINITIONS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*BMM_DEFINITIONS*

h|*Description*
2+a|Definitions used by all BMM packages.

h|*Inherit*
2+|`BASIC_DEFINITIONS`

h|*Constants*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*Bmm_internal_version*: `String`
a|Current internal version of BMM meta-model, used to determine if a given schema can be processed by a given implementation of the model.

h|*1..1*
|*Schema_name_delimiter*: `String{nbsp}={nbsp}"::"`
a|Delimiter used to separate schema id from package path in a fully qualified path.

h|*1..1*
|*Package_name_delimiter*: `String{nbsp}={nbsp}"."`
a|Delimiter used to separate package names in a package path.

h|*1..1*
|*Bmm_schema_file_extension*: `String{nbsp}={nbsp}".bmm"`
a|Extension used for BMM files.

h|*1..1*
|*Generic_left_delimiter*: `Character{nbsp}={nbsp}'<'`
a|Left delimiter for generic class and generic type names, as used in `List<T>`.

h|*1..1*
|*Generic_right_delimiter*: `Character{nbsp}={nbsp}'>'`
a|Right delimiter for generic class and generic type names, as used in `List<T>`.

h|*1..1*
|*Generic_constraint_delimiter*: `Character{nbsp}={nbsp}':'`
a|Right delimiter for generic class names, as used in `Sortable<T: Ordered>`.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*Any_class* (): `BMM_SIMPLE_CLASS`
a|

h|
|*Any_type* (): `BMM_SIMPLE_TYPE`
a|
|===
