=== BMM_PROPERTY Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_PROPERTY (abstract)_*

h|*Description*
2+a|Meta-type of a property definition within a class definition of an object model. The `_is_composition_` attribute indicates whether the property has sub-part or an association semantics with respect to the owning class.

h|*Inherit*
2+|`BMM_INSTANTIABLE`, `BMM_CLASS_SCOPED`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*is_im_runtime*: `Boolean`
a|True if this property is marked with info model `_im_runtime_` property.

h|*0..1*
|*is_im_infrastructure*: `Boolean`
a|True if this property was marked with info model `_im_infrastructure_` flag.

h|*0..1*
|*is_synthesised_generic*: `Boolean`
a|True if this property was synthesised due to generic substitution in an inherited type, or further constraining of a formal generic parameter.

h|*0..1*
|*is_composition*: `Boolean`
a|True if this property instance is a compositional sub-part of the owning class instance. Equivalent to 'composition' in UML associations (but missing from UML properties without associations) and also 'cascade-delete' semantics in ER schemas.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|
|*existence* (): `Multiplicity_interval`
a|Interval form of `0..1`, `1..1` etc, derived from `_is_nullable_`.

h|
|*display_name* (): `String`
a|Name of this property to display in UI.

h|*Invariants*
2+a|*_Inv_signature_no_args_*: `signature.arguments = Void`
|===
