=== BMM_CLASS Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_CLASS (abstract)_*

h|*Description*
2+a|Meta-type corresponding a class definition in an object model. Inheritance is specified by the `_ancestors_` attribute, which contains a list of _types_ rather than classes. Inheritance is thus understood in BMM as a stated relationship between classes. The equivalent relationship between types is conformance.

NOTE: unlike UML, the `_name_` is just the root name, even if the class is generic. Use `_type_name()_` to obtain the qualified type name.

h|*Inherit*
2+|`BMM_ENTITY`, `BMM_DECLARATION`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*ancestors*: `Hash<String,BMM_MODEL_TYPE>`
a|List of immediate inheritance parents.

h|*1..1*
|*package*: `BMM_PACKAGE`
a|Package this class belongs to.

h|*0..1*
|*properties*: `Hash<String,BMM_PROPERTY>`
a|List of attributes defined in this class.

h|*1..1*
|*source_schema_id*: `String`
a|Reference to original source schema defining this class. Useful for UI tools to determine which original schema file to open for a given class for manual editing.

h|*0..1*
|*immediate_descendants*: `List<BMM_CLASS>`
a|List of references to base classes of immediate inheritance descendants, derived when members of `_ancestors_` are attached at creation time.

h|*1..1*
|*is_override*: `Boolean`
a|True if this definition overrides a class of the same name in an included schema.

h|*0..1*
|*constants*: `Hash<String,BMM_CONSTANT>`
a|List of constants defined in this class.

h|*0..1*
|*functions*: `Hash<String,BMM_FUNCTION>`
a|List of functions defined in this class.

h|*0..1*
|*procedures*: `Hash<String,BMM_PROCEDURE>`
a|List of procedures defined in this class.

h|*0..1*
|*is_primitive*: `Boolean`
a|True if this class represents a type considered to be primitive in the type system, i.e. any typically built-in or standard library type such as `String`, `Date`, `Hash<K,V>` etc.

h|*0..1*
|*is_abstract*: `Boolean`
a|True if this class is marked as abstract, i.e. direct instances cannot be created from its direct type.

h|*0..1*
|*invariants*: `List<ASSERTION>`
a|

h|*1..1 +
(redefined)*
|*scope*: `BMM_MODEL`
a|Model within which class is defined.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(abstract)
|*type* (): `BMM_MODEL_TYPE`
a|Generate a type object that represents the type for which this class is the definer.

h|
|*all_ancestors* (): `List<String>`
a|List of all inheritance parent class names, recursively.

h|
|*all_descendants* (): `List<String>`
a|Compute all descendants by following `_immediate_descendants_`.

h|
|*suppliers* (): `List<String>`
a|List of names of immediate supplier classes, including concrete generic parameters, concrete descendants of abstract statically defined types, and inherited suppliers. (Where generics are unconstrained, no class name is added, since logically it would be `Any` and this can always be assumed anyway). This list includes primitive types.

h|
|*suppliers_non_primitive* (): `List<String>`
a|Same as `suppliers` minus primitive types, as defined in input schema.

h|
|*supplier_closure* (): `List<String>`
a|List of names of all classes in full supplier closure, including concrete generic parameters; (where generics are unconstrained, no class name is added, since logically it would be `Any` and this can always be assumed anyway).  This list includes primitive types.

h|
|*package_path* (): `String`
a|Fully qualified package name, of form: `package.package`.

h|
|*class_path* (): `String`
a|Fully qualified class name, of form: `package.package.CLASS` with package path in lower-case and class in original case.

h|(effected)
|*is_primitive* (): `Boolean`
a|True if this class is designated a primitive type within the overall type system of the schema. Set from schema.

h|(effected)
|*is_abstract* (): `Boolean`
a|True if this class is abstract in its model. Value provided from an underlying data property set at creation or construction time.

h|
|*features* (): `List<BMM_CLASS_SCOPED>`
a|List of all feature definitions introduced in this class.

h|
|*flat_features* (): `List<BMM_CLASS_SCOPED>`
a|Consolidated list of all feature definitions from this class and all inheritance ancestors.

h|
|*flat_properties* ()
a|List of all properties due to current and ancestor classes, keyed by property name.
|===
