=== BMM_TYPE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__BMM_TYPE (abstract)__*

h|*Description*
2+a|Abstract idea of specifying a type in some context. This is not the same as 'defining' a class. A type specification is essentially a reference of some kind, that defines the type of an attribute, or function result or argument. It may include generic parameters that might or might not be bound. See subtypes.

h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(abstract)*
|*type_name* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Formal string form of the type as per UML.

h|*1..1*
|*type_signature* (): `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Signature form of the type name, which for generics includes generic parameter constrainer types E.g. `Interval<T:Ordered>`.

Defaults to the value of `_type_name()_`.

h|*1..1 +
(abstract)*
|*is_abstract* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|If true, indicates a type based on an abstract class, i.e. a type that cannot be directly instantiated.

h|*1..1 +
(abstract)*
|*is_primitive* (): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|If True, indicates that a type based solely on primitive classes.

h|*1..1 +
(abstract)*
|*unitary_type* (): `<<_bmm_unitary_type_class,BMM_UNITARY_TYPE>>`
a|Type with any container abstracted away; may be a formal generic type.

h|*1..1 +
(abstract)*
|*effective_type* (): `<<_bmm_effective_type_class,BMM_EFFECTIVE_TYPE>>`
a|Type with any container abstracted away, and any formal parameter replaced by its effective constraint type.

h|*1..1 +
(abstract)*
|*flattened_type_list* (): `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]>`
a|Completely flattened list of type names, flattening out all generic parameters.
|===
