=== BMM_DECLARATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_BMM_DECLARATION (abstract)_*

h|*Description*
2+a|Meta-type of BMM declared model elements. A _declaration_ is a an element of a model _specified by an author within a model definition_ within a context, which defines the _scope_ of the element. Thus, a class definition and its property and routine definitions are model elements, but Types are not, since they are derived from model elements.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `String`
a|Name of this model element.

h|*0..1*
|*documentation*: `Hash<String, Any>`
a|Optional documentation of this element, as a keyed list.

It is strongly recommended to use the following key /type combinations for the relevant purposes:

* `"purpose": String`
* `"keywords": List<String>`
* `"use": String`
* `"misuse": String`
* `"references": String`

Other keys and value types may be freely added.

h|*1..1*
|*scope*: `BMM_DECLARATION`
a|Model element within which an element is declared.

h|*0..1*
|*extensions*: `Hash<String, Any>`
a|Optional meta-data of this element, as a keyed list. May be used to extend the meta-model.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_root_scope* (): `Boolean` +
 +
_Post_result_: `Result = (scope = self)`
a|True if this declaration entity is the root of the declaration hierarchy.
|===
