=== EL_AGENT Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*_EL_AGENT (abstract)_*

h|*Description*
2+a|A delayed routine call, whose arguments may be open, partially closed or closed. Instances may include closed delayed calls like `calculate_age (dob="1987-09-13", today="2019-06-03")` but also partially open calls such as `format_structure (struct=?, style=3)`, where `struct` is an open argument.

Effective type (i.e. type of runtime evaluated form) is `BMM_SIGNATURE`.

h|*Inherit*
2+|`EL_TERMINAL`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*name*: `String`
a|Name of the routine being called.

h|*0..1*
|*closed_args*: `EL_TUPLE`
a|Closed arguments of a routine call as a tuple of objects.

h|*0..1*
|*open_args*: `List<String>`
a|Optional list of names of open arguments of the call. If not provided, and the `_name_` refers to a routine with more arguments than supplied in `_closed_args_`, the missing arguments are inferred from the `_definition_`.

h|*0..1*
|*definition*: `BMM_ROUTINE`
a|Reference to definition of a routine for which this is an agent, if one exists.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|(effected)
|*eval_type* (): `BMM_SIGNATURE` +
 +
_Post_result_: `Result = definition.signature`
a|Eval type is the signature corresponding to the (remaining) open arguments and return type, if any.

h|
|*is_callable* (): `Boolean` +
 +
_Post_result_validity_: `Result = open_arguments = Void`
a|True if there are no open arguments.
|===
