include::partial$module_vars.adoc[]

//
// ============================================ Asciidoc HEADER =============================================
//

//
// ============================================ Asciidoc PREAMBLE =============================================
//


= {spec_title} [.spec-status.spec-status-development]#{spec_status}#

== Purpose

This document specifies an abstract openEHR Expression Language (openEHR EL) that provides a syntax counterpart to the `expression` package in the {openehr_bmm}[openEHR Basic Meta-Model (BMM)^]. This may be used within BMM models, to specify archetype rules, and in decision language expressions.

The intended audience includes:

* Standards bodies producing health informatics standards;
* Academic groups using openEHR;
* Solution vendors.

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^];
* The {openehr_bmm}[openEHR Basic Meta-Model (BMM)^]

Releated documents include:

* The {openehr_am_aom2}[Archetype Object Model 2 (AOM2)^], Assertions section;
* The {openehr_task_planning}[Task Planning specification^];
* The {openehr_cds_gdl}[Guideline Definition Language (GDL)^].





//
// ============================================= Asciidoc BODY ===============================================
//


//
// --------------------------------------------- Preface -----------------------------------------------
//

== Feedback

Feedback may be provided on the {openehr_lang_forum}[openEHR languages specifications forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].


